// Generated by CoffeeScript 1.8.0
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

window.AppView = (function(_super) {
  __extends(AppView, _super);

  function AppView() {
    return AppView.__super__.constructor.apply(this, arguments);
  }

  AppView.prototype.template = _.template('<button class="hit-button button">Hit</button> <button class="stand-button button">Stand</button> <div class="winner"></div> <div class="player-hand-container"></div> <div class="dealer-hand-container"></div>');

  AppView.prototype.events = {
    'click .hit-button': function() {
      return this.model.get('playerHand').playerHit();
    },
    'click .stand-button': function() {
      return this.model.get('dealerHand').stand();
    }
  };

  AppView.prototype.initialize = function() {
    this.model.get('dealerHand').on({
      'stand': (function(_this) {
        return function() {
          return _this.$el.find('.button').attr('disabled', 'true');
        };
      })(this)
    });
    this.model.get('playerHand').on({
      'bust': (function(_this) {
        return function() {
          _this.$el.find('.button').attr('disabled', 'true');
          _this.model.winner();
          return _this.renderWinner();
        };
      })(this)
    });
    this.model.get('dealerHand').on({
      'stop': (function(_this) {
        return function() {
          _this.model.winner();
          return _this.renderWinner();
        };
      })(this)
    });
    return this.render();
  };

  AppView.prototype.render = function() {
    this.$el.children().detach();
    this.$el.html(this.template());
    this.$('.player-hand-container').html(new HandView({
      collection: this.model.get('playerHand')
    }).el);
    return this.$('.dealer-hand-container').html(new HandView({
      collection: this.model.get('dealerHand')
    }).el);
  };

  AppView.prototype.renderWinner = function() {
    return this.$el.find('.winner').text("The " + (this.model.get('winner')) + " has won");
  };

  return AppView;

})(Backbone.View);
